<?php
function getTemplate() {
	$template = '<header>
	<img src="pages/common-img/marbust-h-logo.png" class="top-logo">
	</header>
	<hr>
	<h1>Usuarios Registrados</h1>
	<p>Estimado <strong>'.$_SESSION['userData']['accountName'].'</strong> estos son los usuarios registrados en tu Sistema de <strong>Marbust Accounts®:</strong></p>
	<div class="table-container">
	<table>
			<thead>
				<tr>
					<th>ID</th>
					<th>Nombre</th>
					<th>Teléfono</th>
					<th>Email</th>
				</tr>
			</thead>
			<tbody>';
	PDFController::GetAllAccountsController();
                foreach ($_SESSION['accountsData'] as $accountData) {
                    $template = $template.'<tr>';
                    $template = $template.'<td>'.$accountData["MarbustAccountId"].'</td>';
                    $template = $template.'<td>'.$accountData["accountName"].'</td>';
                    $template = $template.'<td>'.$accountData["accountEmail"].'</td>';
                    $template = $template.'<td>'.$accountData["accountPhone"].'</td>';
                    $template = $template.'</tr>';
                }
	$template = $template.'</table>';
	$template = $template.'</div>
	<footer>
	<hr>
	<p>Report generated by: <a href="https://accounts.marbust.com">Marbust Accounts® System</a><br>At: '.date('d-m-y h:i:s').'<br>&copy; '.date("Y").' <strong>Marbust Technology Company</strong> - All Rights Reserved</p>
	</footer>';
	return $template;
}


	?>