<?php
function getTemplate() {
	$template = '<header>
	<img src="pages/common-img/marbust-h-logo.png" class="top-logo">
	</header>
	<hr>
	<h1>Mis Mantenimientos</h1>
	<p>Estimado/s <strong>'.$_SESSION['userData']['accountName'].'</strong> estos son los mantenimientos registrados en tu cuenta de <strong>Marbust Accounts®:</strong></p>
	<div class="table-container">
	<table>
			<thead>
				<tr>
					<th>ID</th>
					<th>Computadora</th>
					<th>Fecha</th>
					<th>Tipo</th>
					<th>Técnico</th>
				</tr>
			</thead>
			<tbody>';
	PDFController::GetMyMaintancesController();
                foreach ($_SESSION['myMaintancesData'] as $accountData) {
					$year = $accountData["maintancedoneYear"];
                    $month = $accountData["maintancedoneMonth"];
                    $month = functions::MesName($month);
                    $day = $accountData["maintancedoneDay"];
                    $template = $template.'<tr>';
                    $template = $template.'<td>'.$accountData["maintancecomputerId"].'</td>';
					$template = $template.'<td>'.$accountData["maintancecomputerName"].'</td>';
					$template = $template.'<td>'.$month.' '.$day.', '.$year.'</td>';
					$template = $template.'<td>'.$accountData["maintancetypeName"].'</td>';
					$techName = Datos::GetSpecificTechNameModel($accountData["maintancetechId"]);
                    $template = $template.'<td>'.$techName["accountName"].'</td>';
                    $template = $template.'</tr>';
                }
	$template = $template.'</table>';
	$template = $template.'</div>
	<footer>
	<hr>
	<p>Report generated by: <a href="https://accounts.marbust.com">Marbust Accounts® System</a><br>At: '.date('d-m-y h:i:s').'<br>&copy; '.date("Y").' <strong>Marbust Technology Company</strong> - All Rights Reserved</p>
	</footer>';
	
	return $template;
}


	?>