<?php
function getTemplate() {
	$template = '<header>
	<img src="pages/common-img/marbust-h-logo.png" class="top-logo">
	</header>
	<hr>
	<h1>Reporte de Mantenimiento</h1>
	<p>Estimado/s <strong>'.$_SESSION['userData']['accountName'].'</strong> este es el informe que tenemos sobre el mantenimiento realizado en nuestro sistema de <strong>Marbust Computers®:</strong></p>';
	$GetMaintanceData = Datos::GetMaintanceData( $_SESSION["SelectedUserMaintanceid"] );
	$year = $GetMaintanceData["maintancedoneYear"];
    $month = $GetMaintanceData["maintancedoneMonth"];
    $month = functions::MesName($month);
	$day = $GetMaintanceData["maintancedoneDay"];
	$template = $template.'<p><strong>Id: </strong>'.$GetMaintanceData["maintanceId"].'</p>';
	$template = $template.'<p><strong>Fecha: </strong>'.$month.' '.$day.', '.$year.'</p>';
	if ($_SESSION['SUPERADMIN'] == TRUE) {
		$template = $template.'<p><strong>Cliente: </strong>'.$GetMaintanceData["accountName"].'</p>';
	}
	$template = $template.'<p><strong>Computadora: </strong>'.$GetMaintanceData["maintancecomputerName"].'</p>';
	$template = $template.'<p><strong>Tipo: </strong>'.$GetMaintanceData["maintancetypeName"].'</p>';
	$techName = Datos::GetSpecificTechNameModel($GetMaintanceData["maintancetechId"]);
	$template = $template.'<p><strong>Técnico: </strong>'.$techName["accountName"].'</p>';
	$promo = $GetMaintanceData["maintancePromo"];
                    if ($promo == "1") {
                        $promo = "Si";
                    } else {
                        $promo = "No";
                    }
	$template = $template.'<p><strong>Descuento aplicado: </strong>'.$promo.'</p>';
	$template = $template.'<br><h2>Informe</h2><hr>';
	$template = $template.'<p>'.$GetMaintanceData["maintanceDescription"].'</p>';
	$Nyear = $GetMaintanceData["maintancenextYear"];
    $Nmonth = $GetMaintanceData["maintancenextMonth"];
    $Nmonth = functions::MesName($Nmonth);
	$Nday = $GetMaintanceData["maintancenextDay"];
	$template = $template.'<br><p>Se recomienda realizar su próximo mantenimiento antes de: <strong>'.$Nmonth.' '.$Nday.', '.$Nyear.'</strong></p>';
	$template = $template.'<footer>
	<hr>
	<p>Report generated by: <a href="https://accounts.marbust.com">Marbust Accounts® System</a><br>At: '.date('d-m-y h:i:s').'<br>&copy; '.date("Y").' <strong>Marbust Technology Company</strong> - All Rights Reserved</p>
	</footer>';
	
	return $template;
}


	?>